// Code generated by ogen, DO NOT EDIT.

package privategptclient

// setDefaults set default value of fields.
func (s *ChatBody) setDefaults() {
	{
		val := bool(false)
		s.UseContext.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeSources.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChunksBody) setDefaults() {
	{
		val := int(10)
		s.Limit.SetTo(val)
	}
	{
		val := int(0)
		s.PrevNextChunks.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CompletionsBody) setDefaults() {
	{
		val := bool(false)
		s.UseContext.SetTo(val)
	}
	{
		val := bool(true)
		s.IncludeSources.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *HealthResponse) setDefaults() {
	{
		val := string("ok")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAIChoice) setDefaults() {
	{
		val := int(0)
		s.Index.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAICompletion) setDefaults() {
	{
		val := OpenAICompletionObject("completion")
		s.Object.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *OpenAIMessage) setDefaults() {
	{
		val := OpenAIMessageRole("user")
		s.Role.SetTo(val)
	}
}
