// Code generated by ogen, DO NOT EDIT.

package privategptclient

// DeleteIngestedV1IngestDocIDDeleteParams is parameters of delete_ingested_v1_ingest__doc_id__delete operation.
type DeleteIngestedV1IngestDocIDDeleteParams struct {
	DocID string
}
