// Code generated by ogen, DO NOT EDIT.
package privategptclient

type ChatCompletionV1ChatCompletionsPostRes interface {
	chatCompletionV1ChatCompletionsPostRes()
}

type ChunksRetrievalV1ChunksPostRes interface {
	chunksRetrievalV1ChunksPostRes()
}

type DeleteIngestedV1IngestDocIDDeleteRes interface {
	deleteIngestedV1IngestDocIDDeleteRes()
}

type EmbeddingsGenerationV1EmbeddingsPostRes interface {
	embeddingsGenerationV1EmbeddingsPostRes()
}

type IngestFileV1IngestFilePostRes interface {
	ingestFileV1IngestFilePostRes()
}

type IngestTextV1IngestTextPostRes interface {
	ingestTextV1IngestTextPostRes()
}

type IngestV1IngestPostRes interface {
	ingestV1IngestPostRes()
}

type PromptCompletionV1CompletionsPostRes interface {
	promptCompletionV1CompletionsPostRes()
}
